In [1]:
%time 1+2

Wall time: 0 ns


3

In [2]:
strings = ['foo','foobar','baz','qux','python','gui do'] *1000
%timeit [x for x in strings if x.startswith('foo')]

1.63 ms ± 17 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
import os
os.getcwd()
#f =open('')

'C:\\Users\\lorin\\Documents\\Python File'

In [4]:
f =open('txt.txt','r')

In [5]:
f.read()

'世界第一\n宇宙无敌'

In [7]:
with open ('txt.txt') as p:
    print(p.read())

世界第一
宇宙无敌


In [8]:
with open ('txt.txt') as p:
    print(p.readline())

世界第一



In [10]:
with open ('txt.txt') as p:
    for line in p.readlines():
        print(line.strip())

世界第一
宇宙无敌


In [11]:
with open ('txt1.txt','w') as d:
    d.write("mother fucker")

In [13]:
from io import StringIO
f = StringIO()
f.write('hello,worl')
print(f.getvalue())

hello,worl


In [14]:
from io import BytesIO
f = BytesIO()
f.write('english'.encode('utf-8'))

7

In [15]:
print(f.getvalue())

b'english'


In [20]:
import os
os.name
#os.uname()

'nt'

In [21]:
os.path.abspath('.')

'C:\\Users\\lorin\\Documents\\Python File'

In [25]:
import numpy as np
list1 = [1,2,3,4,5]
a = 10
mymatrix = np.mat(list1)
print(a*mymatrix)

[[10 20 30 40 50]]


In [26]:
mx1 = np.zeros([3,5])
print(mx1)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [27]:
mx2 = np.random.rand(3,4)
print(mx2)

[[ 0.15828925  0.21037483  0.74807338  0.60769044]
 [ 0.09486521  0.79511205  0.37104549  0.48742185]
 [ 0.88330979  0.15153805  0.24849817  0.97932418]]


In [33]:
data = [[1.1,1.2,1.3],[2.1,2.2,2.3]]
data1 = np.array(data)
print(data1)

[[ 1.1  1.2  1.3]
 [ 2.1  2.2  2.3]]


In [34]:
data1

array([[ 1.1,  1.2,  1.3],
       [ 2.1,  2.2,  2.3]])

In [35]:
data1.ndim

2

In [36]:
data1.shape

(2, 3)

In [37]:
data1.dtype

dtype('float64')

In [38]:
np.array(5)

array(5)

In [39]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [43]:
ny1 = np.array([1,2,3])

In [44]:
ny1.dtype

dtype('int32')

In [45]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [46]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [47]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [49]:
ay1 = np.arange(10)

In [50]:
ay1[5]

5

In [51]:
ay1[5:8]

array([5, 6, 7])

In [59]:
ay2 = ay1[:3]

In [60]:
ay2

array([0, 1, 2])

In [61]:
ay2[0] = 100

In [62]:
ay1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [64]:
ay3 = np.array([[[1,2,3],[4,5,6]],[[7,8,8],[9,10,11]]])
ay3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  8],
        [ 9, 10, 11]]])

In [65]:
ay3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
cy1 = ay3[0].copy() 

In [70]:
ay3[0] = 666
ay3
ay3[0] = cy1
ay3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  8],
        [ 9, 10, 11]]])

In [1]:
import numpy as np
names=np.array(['bob','cat','dog']) 

In [2]:
names

array(['bob', 'cat', 'dog'], 
      dtype='<U3')

In [7]:
data5 = np.random.randn(3,4)
data5

array([[ 1.43697187, -0.91353082,  0.58320371,  1.34341279],
       [-1.01628297,  0.20433884,  0.5609284 , -0.21078251],
       [ 1.18004791,  0.26036109, -0.74396548,  0.52390125]])

In [8]:
names=='cat'

array([False,  True, False], dtype=bool)

In [9]:
data5[names=='dog']

array([[ 1.18004791,  0.26036109, -0.74396548,  0.52390125]])

In [2]:
import numpy as np
mx6=np.ones([3,3])
mx7=np.eye(3)

In [3]:
mx6+mx7

array([[ 2.,  1.,  1.],
       [ 1.,  2.,  1.],
       [ 1.,  1.,  2.]])

In [4]:
mx6-mx7

array([[ 0.,  1.,  1.],
       [ 1.,  0.,  1.],
       [ 1.,  1.,  0.]])

In [7]:
np.sum(mx6)

9.0

In [9]:
from numpy import *

In [10]:
multiply(mx6,mx7)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [11]:
mx8=mat([1,2,3],[4,5,6],[7,8,9])
mx9=mat([1],[2],[3])
mx8*mx9

TypeError: asmatrix() takes from 1 to 2 positional arguments but 3 were given