In [2]:
from numpy import *

In [3]:
mx1 = mat([[1,2,3],[4,5,6],[7,8,9]])
mx2 = mat([[1],[2],[3]])
print(mx1*mx2)

[[14]
 [32]
 [50]]


In [5]:
print(mx1.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [6]:
print(mx1.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
print(mx1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
[m,n] = shape(mx1)
print(m,n)

3 3


In [11]:
line1 = mx1[0]
print(line1)

[[1 2 3]]


In [12]:
print(linalg.det(mx1))

6.66133814775e-16


In [14]:
print(linalg.inv(mx1))

[[ -4.50359963e+15   9.00719925e+15  -4.50359963e+15]
 [  9.00719925e+15  -1.80143985e+16   9.00719925e+15]
 [ -4.50359963e+15   9.00719925e+15  -4.50359963e+15]]


In [ ]:
#对称矩阵等于实矩阵乘以转置矩阵

In [16]:
linalg.matrix_rank(mx1)

2

In [ ]:
# 数学因为反映本质，所以精炼。因为应用普遍，所以抽象

In [5]:
mx5=mat([[1,1,0,1,0]])
mx6= mat([[0,1,1,0,0]])
print(shape(nonzero(mx5-mx6)))

(2, 3)
