In [1]:
from numpy import *

In [3]:
a  = [[8,1,6],[3,5,7],[4,9,2]]
evals,evecs = linalg.eig(a)
print(evals,evecs)

[ 15.           4.89897949  -4.89897949] [[-0.57735027 -0.81305253 -0.34164801]
 [-0.57735027  0.47140452 -0.47140452]
 [-0.57735027  0.34164801  0.81305253]]


In [4]:
type(a)

list