In [1]:
import numpy as np

In [5]:
mx1 = np.mat([[88.5,96.8],[88.5,96.8]])
corr_coef = np.corrcoef(mx1)
print(corr_coef)

[[ 1.  1.]
 [ 1.  1.]]


In [6]:
type(corr_coef)

numpy.ndarray

In [7]:
lt1 = [[8,1,6],[3,5,7],[4,9,2]]
type(lt1)

list

In [8]:
evals,evecs = np.linalg.eig(lt1)
print("evals:",evals,"\nevecs:",evecs)

evals: [ 15.           4.89897949  -4.89897949] 
evecs: [[-0.57735027 -0.81305253 -0.34164801]
 [-0.57735027  0.47140452 -0.47140452]
 [-0.57735027  0.34164801  0.81305253]]


In [9]:
type(evecs)

numpy.ndarray