In [1]:
from numpy import *

In [2]:
mx1 = mat([[1,2,3],[4,5,6],[7,8,9]])
type(mx1)

numpy.matrixlib.defmatrix.matrix

In [4]:
mx2 = mat([[0,0,0],[4,5,6],[7,8,9]])
print(linalg.det(mx2))

0.0


6.66133814775e-16


In [6]:
mx2 = linalg.inv(mx1)
print(mx2)

[[ -4.50359963e+15   9.00719925e+15  -4.50359963e+15]
 [  9.00719925e+15  -1.80143985e+16   9.00719925e+15]
 [ -4.50359963e+15   9.00719925e+15  -4.50359963e+15]]


In [7]:
print(linalg.matrix_rank(mx1))

2


In [10]:
a = [8,1,6]
print(linalg.norm(a))

10.0498756211


In [12]:
mx3 = mat([[1,2,3],[1,2,3]])
print(corrcoef(mx3))

[[ 1.  1.]
 [ 1.  1.]]


In [14]:
print(type(mx3))

<class 'numpy.matrixlib.defmatrix.matrix'>
