In [1]:
import numpy as np

In [3]:
lt1 =  [1,2,3,4,5]
a = 10
mx1 = np.mat(lt1)
print(a*mx1)

[[10 20 30 40 50]]


In [4]:
mx2 = np.zeros([3,5])
print(mx2)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [5]:
mx3 = np.eye(4)
print(mx3)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [6]:
mx4 = np.random.rand(4,4)
print(mx4)

[[ 0.7132831   0.13389538  0.55463825  0.36527622]
 [ 0.88365736  0.7118838   0.24783683  0.15754304]
 [ 0.21126945  0.06316495  0.28968652  0.77831481]
 [ 0.90243084  0.29037091  0.14103854  0.91460489]]


In [7]:
mx5 = mx3+mx4
print(mx5)

[[ 1.7132831   0.13389538  0.55463825  0.36527622]
 [ 0.88365736  1.7118838   0.24783683  0.15754304]
 [ 0.21126945  0.06316495  1.28968652  0.77831481]
 [ 0.90243084  0.29037091  0.14103854  1.91460489]]


In [8]:
print(10*mx5)

[[ 17.13283102   1.33895376   5.54638246   3.6527622 ]
 [  8.83657362  17.11883799   2.47836835   1.5754304 ]
 [  2.11269453   0.63164945  12.8968652    7.78314809]
 [  9.02430836   2.90370907   1.41038543  19.14604893]]


In [11]:
np.sum(mx3)
sum(mx3)

array([ 1.,  1.,  1.,  1.])

In [12]:
mx6 = 1.5*mx3
mx6

array([[ 1.5,  0. ,  0. ,  0. ],
       [ 0. ,  1.5,  0. ,  0. ],
       [ 0. ,  0. ,  1.5,  0. ],
       [ 0. ,  0. ,  0. ,  1.5]])

In [14]:
print(np.sum(mx3))

4.0


In [15]:
mx7 = np.multiply(mx3,mx6)
print(mx7)

[[ 1.5  0.   0.   0. ]
 [ 0.   1.5  0.   0. ]
 [ 0.   0.   1.5  0. ]
 [ 0.   0.   0.   1.5]]


In [16]:
type(mx7)

numpy.ndarray

In [18]:
mx8 = np.power(mx7,2)
print(mx8)

[[ 2.25  0.    0.    0.  ]
 [ 0.    2.25  0.    0.  ]
 [ 0.    0.    2.25  0.  ]
 [ 0.    0.    0.    2.25]]


In [19]:
mx9 = np.random.rand(4,4)
print(mx9)

[[ 0.94795093  0.59502274  0.40005458  0.8469435 ]
 [ 0.822853    0.68156636  0.05644749  0.31123869]
 [ 0.85776907  0.613588    0.78598109  0.02164572]
 [ 0.96439142  0.42351041  0.38844739  0.11972071]]


In [20]:
print(mx9.T)

[[ 0.94795093  0.822853    0.85776907  0.96439142]
 [ 0.59502274  0.68156636  0.613588    0.42351041]
 [ 0.40005458  0.05644749  0.78598109  0.38844739]
 [ 0.8469435   0.31123869  0.02164572  0.11972071]]


In [22]:
print(mx9.transpose())
print(mx9)

[[ 0.94795093  0.822853    0.85776907  0.96439142]
 [ 0.59502274  0.68156636  0.613588    0.42351041]
 [ 0.40005458  0.05644749  0.78598109  0.38844739]
 [ 0.8469435   0.31123869  0.02164572  0.11972071]]
[[ 0.94795093  0.59502274  0.40005458  0.8469435 ]
 [ 0.822853    0.68156636  0.05644749  0.31123869]
 [ 0.85776907  0.613588    0.78598109  0.02164572]
 [ 0.96439142  0.42351041  0.38844739  0.11972071]]
