In [1]:
from numpy import *

In [5]:
lt1 = [[1,2,3],[4,5,6]] 
mx1 = array(lt1)
print(type(mx1))

<class 'numpy.ndarray'>


In [3]:
mx1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
list3 = [[1,2,3],[4,5,6],[7,8,9]]
print(type(list3))

<class 'list'>


In [7]:
mx3 = mat(list3)
print(type(mx3))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [8]:
mx4 = array(list3)
print(type(mx4))

<class 'numpy.ndarray'>


In [9]:
ay1 = array([1.1,2.2,3.3])
ay1

array([ 1.1,  2.2,  3.3])

In [12]:
ay1.astype(int32)

array([1, 2, 3])

In [ ]:
#astype函数转换了ndarray的数据类型，截断了小数部分

In [13]:
arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [15]:
ay2 = array([[1.,2.,3.],[4.,5.,6.]])


In [16]:
ay2.dtype

dtype('float64')

In [17]:
ay2 * ay2

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [19]:
ay3 = arange(9)
ay3[5]

5

In [20]:
lt5 = [1,2,3,4,5]
lt5[2]

3

In [21]:
lt5[:]

[1, 2, 3, 4, 5]