In [3]:
import numpy as np
my_zero =  np.zeros([3,5])
print(my_zero)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [5]:
rand_mx = np.random.rand(3,4)
print(rand_mx)

[[ 0.92028532  0.38242302  0.61236415  0.20823462]
 [ 0.03333187  0.73766267  0.10266636  0.95082243]
 [ 0.67679125  0.86573413  0.40237639  0.87125502]]


In [6]:
idty_mx = np.random.rand(3)
print(idty_mx)

[ 0.63838064  0.6840272   0.65669813]


In [7]:
mx = np.mat([[1,2,3],[4,5,6],[7,8,9]])
print(mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
mx = mx.T
print(mx)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
a = np.linalg.det(mx)
print(a)

0.0


In [16]:
mx3 = np.mat([[1,2],[3,4]])
mx_inv = np.linalg.inv(mx3)
print(mx_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [15]:
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print(x) 
print(y) 
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[  1.00000000e+00   1.11022302e-16]
 [  0.00000000e+00   1.00000000e+00]]


In [17]:
b = np.linalg.det(mx3)
print(b)

-2.0
